apiVersion: v1
kind: Service
metadata:
  name: employer-service
  labels:
    app: employer-service
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 4001
  selector:
    app: ctse-app
  sessionAffinity: None